//login
export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";

//mentors actions
export const GET_MENTORS_REQUESTED = "GET_MENTORS_REQUESTED";
export const GET_MENTORS_SUCCESS = "GET_MENTORS_SUCCESS";
export const GET_MENTORS_FAILED = "GET_MENTORS_FAILED";

//create Mentor
export const CREATE_MENTORS_REQUESTED = "CREATE_MENTORS_REQUESTED";
export const CREATE_MENTORS_SUCCESS = "CREATE_MENTORS_SUCCESS";
export const CREATE_MENTORS_FAILED = "CREATE_MENTORS_FAILED";
//update mentor
export const UPDATE_MENTORS_REQUESTED = "UPDATE_MENTORS_REQUESTED";
export const UPDATE_MENTORS_SUCCESS = "UPDATE_MENTORS_SUCCESS";
export const UPDATE_MENTORS_FAILED = "UPDATE_MENTORS_FAILED";
//delete mentor
export const DELETE_MENTORS_REQUESTED = "DELETE_MENTORS_REQUESTED";
export const DELETE_MENTORS_SUCCESS = "DELETE_MENTORS_SUCCESS";
export const DELETE_MENTORS_FAILED = "DELETE_MENTORS_FAILED";

//get task
export const GET_TASKS_REQUESTED = "GET_TASKS_REQUESTED";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASKS_FAILED = "GET_TASKS_FAILED";

//update task
export const UPDATE_TASKS_REQUESTED = "UPDATE_TASKS_REQUESTED";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASKS_FAILED = "UPDATE_TASKS_FAILED";

//delete task
export const DELETE_TASKS_REQUESTED = "DELETE_TASKS_REQUESTED";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASKS_FAILED = "DELETE_TASKS_FAILED";

//create task
export const CREATE_TASKS_REQUESTED = "CREATE_TASKS_REQUESTED";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASKS_FAILED = "CREATE_TASKS_FAILED";

//logoutUser
export const LOGOUT_USERS_REQUESTED = "LOGOUT_USERS_REQUESTED";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILED = "CREATE_TASKS_FAILED";
